/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vendingmachine;

/**
 *
 * @author Darryl
 */
public class TestVendingMenu extends javax.swing.JFrame {

    Owner authorizedOwner;
    RegularVendingMachine authenticatedRegularMachine = null;
    SpecialVendingMachine authenticatedSpecialMachine = null;

    /**
     * Creates new form TestVendingMenu
     */
    public TestVendingMenu() {
        initComponents();
        regularVendingButton.setEnabled(false);
        specialVendingButton.setEnabled(false);
    }

    public TestVendingMenu(Owner owner) {
        this();
        authorizedOwner = owner;

        for (RegularVendingMachine regularMachine : authorizedOwner.getRegularMachines()) {
            regularVendingList.addItem(regularMachine.getName());
        }

        for (SpecialVendingMachine specialMachine : authorizedOwner.getSpecialMachines()) {
            specialVendingList.addItem(specialMachine.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        regularVendingButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        specialVendingButton = new javax.swing.JButton();
        regularVendingList = new javax.swing.JComboBox<>();
        specialVendingList = new javax.swing.JComboBox<>();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        regularVendingButton.setFont(new java.awt.Font("Century Gothic", 1, 21)); // NOI18N
        regularVendingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingmachine/TestRVMButton.png"))); // NOI18N
        regularVendingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regularVendingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regularVendingButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingmachine/VendingMachineIcon.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(254, 109, 115));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TEST VENDING MACHINE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(221, 221, 221))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        specialVendingButton.setFont(new java.awt.Font("Century Gothic", 1, 21)); // NOI18N
        specialVendingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendingmachine/TestSVMButton.png"))); // NOI18N
        specialVendingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        specialVendingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialVendingButtonActionPerformed(evt);
            }
        });

        regularVendingList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regularVendingListActionPerformed(evt);
            }
        });

        specialVendingList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialVendingListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(specialVendingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regularVendingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regularVendingList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(specialVendingList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(regularVendingList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regularVendingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(specialVendingList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(specialVendingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regularVendingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regularVendingButtonActionPerformed
        // Testing Regular Vending Machine
        RegularVM regularVendingMachine = new RegularVM(authorizedOwner, authenticatedRegularMachine);
        regularVendingMachine.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_regularVendingButtonActionPerformed

    private void specialVendingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialVendingButtonActionPerformed
        // Testing Special Vending Machine
        SpecialVM specialVendingMaintenance = new SpecialVM(authorizedOwner, authenticatedSpecialMachine);
        specialVendingMaintenance.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_specialVendingButtonActionPerformed

    private void regularVendingListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regularVendingListActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == regularVendingList) {
            String machineName = regularVendingList.getSelectedItem().toString();
            authenticatedRegularMachine = authorizedOwner.getRegularMachine(machineName);
            regularVendingButton.setEnabled(true);
        }
    }//GEN-LAST:event_regularVendingListActionPerformed

    private void specialVendingListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialVendingListActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == specialVendingList) {
            String machineName = specialVendingList.getSelectedItem().toString();
            authenticatedSpecialMachine = authorizedOwner.getSpecialMachine(machineName);
            specialVendingButton.setEnabled(true);
        }
    }//GEN-LAST:event_specialVendingListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestVendingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestVendingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestVendingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestVendingMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestVendingMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton regularVendingButton;
    private javax.swing.JComboBox<String> regularVendingList;
    private javax.swing.JButton specialVendingButton;
    private javax.swing.JComboBox<String> specialVendingList;
    // End of variables declaration//GEN-END:variables
}
