package vendingmachine;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;

/**
 * This class represents the testing of the maintenance menu of the regular
 * vending machine
 *
 * @author Andrea Dulin and Darryl Javier
 */
public class TestRegularMaintenanceView extends javax.swing.JFrame {

    /**
     * Creates new form TestMaintenance
     */
    public TestRegularMaintenanceView() {
        initComponents();
        setLocationRelativeTo(null);
        addStockBtn.setVisible(false);
        transactionSummaryBtn.setVisible(false);
        replenishBtn.setVisible(false);
        collectMoneyBtn.setVisible(false);
        restockBtn.setVisible(false);
        changePriceBtn.setVisible(false);
    }

    public JComboBox<String> getRegularMachineComboBox() {
        return regularMachineComboBox;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addStockBtn = new javax.swing.JButton();
        transactionSummaryBtn = new javax.swing.JButton();
        replenishBtn = new javax.swing.JButton();
        collectMoneyBtn = new javax.swing.JButton();
        restockBtn = new javax.swing.JButton();
        changePriceBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        regularMachineComboBox = new javax.swing.JComboBox<>();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(254, 249, 239));

        jPanel2.setBackground(new java.awt.Color(254, 109, 115));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TEST REGULAR VENDING MACHINE MAINTENANCE FEATURES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        addStockBtn.setBackground(new java.awt.Color(34, 124, 157));
        addStockBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        addStockBtn.setForeground(new java.awt.Color(255, 255, 255));
        addStockBtn.setText("Add Stock");
        addStockBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        transactionSummaryBtn.setBackground(new java.awt.Color(34, 124, 157));
        transactionSummaryBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        transactionSummaryBtn.setForeground(new java.awt.Color(255, 255, 255));
        transactionSummaryBtn.setText("Transaction Summary");
        transactionSummaryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        replenishBtn.setBackground(new java.awt.Color(34, 124, 157));
        replenishBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        replenishBtn.setForeground(new java.awt.Color(255, 255, 255));
        replenishBtn.setText("Replenish Money");
        replenishBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        collectMoneyBtn.setBackground(new java.awt.Color(34, 124, 157));
        collectMoneyBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        collectMoneyBtn.setForeground(new java.awt.Color(255, 255, 255));
        collectMoneyBtn.setText("Collect Money");
        collectMoneyBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        restockBtn.setBackground(new java.awt.Color(34, 124, 157));
        restockBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        restockBtn.setForeground(new java.awt.Color(255, 255, 255));
        restockBtn.setText("Restock");
        restockBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        changePriceBtn.setBackground(new java.awt.Color(34, 124, 157));
        changePriceBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        changePriceBtn.setForeground(new java.awt.Color(255, 255, 255));
        changePriceBtn.setText("Change Price");
        changePriceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Select Regular Machine:");

        backBtn.setText("Back");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(replenishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(collectMoneyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(restockBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changePriceBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transactionSummaryBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regularMachineComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(regularMachineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(collectMoneyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replenishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changePriceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addStockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transactionSummaryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This is changing the prices of the items
     *
     * @param evt which is an action event of an element
     */
    public void addChangePriceListener(ActionListener listenForChangePrice) {
        changePriceBtn.addActionListener(listenForChangePrice);
    }

    /**
     * This is adding stock of the items
     *
     * @param evt which is an action event of an element
     */
    public void addStockListener(ActionListener listenForAddStock) {
        addStockBtn.addActionListener(listenForAddStock);
    }

    /**
     * This is restocking the items
     *
     * @param evt which is an action event of an element
     */
    public void addRestockListener(ActionListener listenForRestock) {
        restockBtn.addActionListener(listenForRestock);
    }

    /**
     * This is collecting the money from the regular vending machine
     *
     * @param evt which is an action event of an element
     */
    public void addCollectMoneyListener(ActionListener listenForCollectMoney) {
        collectMoneyBtn.addActionListener(listenForCollectMoney);
    }

    /**
     * This is for replenishing the money in the regular vending machine
     *
     * @param evt which is an action event of an element
     */
    public void addReplenishListener(ActionListener listenForReplenish) {
        replenishBtn.addActionListener(listenForReplenish);
    }

    /**
     * This is for displaying the transaction summary of the regular vending
     * machine
     *
     * @param evt which is an action event of an element
     */
    public void addTransactionSummaryListener(ActionListener listenForTransactionSummary) {
        transactionSummaryBtn.addActionListener(listenForTransactionSummary);
    }

    public void revealOptions() {
        addStockBtn.setVisible(true);
        transactionSummaryBtn.setVisible(true);
        replenishBtn.setVisible(true);
        collectMoneyBtn.setVisible(true);
        restockBtn.setVisible(true);
        changePriceBtn.setVisible(true);
    }

    /**
     * This is for displaying the buttons that are the options of the user in
     * maintenance menu when the user have chosen a machine to test maintenance
     * on
     *
     * @param evt which is an action event of an element
     */
    public void addRegularMachineChangeListener(ActionListener listenForRegularMachineChange) {
        regularMachineComboBox.addActionListener(listenForRegularMachineChange);
    }

    /**
     * This is for redirecting the user back to the test maintenance menu
     *
     * @param evt which is an action event of an element
     */
    public void addBackButtonListener(ActionListener listenForBackButton) {
        backBtn.addActionListener(listenForBackButton);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestRegularMaintenanceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestRegularMaintenanceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestRegularMaintenanceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestRegularMaintenanceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestRegularMaintenanceView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStockBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton changePriceBtn;
    private javax.swing.JButton collectMoneyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> regularMachineComboBox;
    private javax.swing.JButton replenishBtn;
    private javax.swing.JButton restockBtn;
    private javax.swing.JButton transactionSummaryBtn;
    // End of variables declaration//GEN-END:variables
}
